//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Project1.rc
//
#define IDD_INISIARSESION               101
#define IDD_REGISTRO                    103
#define IDR_MENU1                       105
#define IDD_INFVENDEDOR                 106
#define IDD_NUEVOPRODUCTO               108
#define IDD_ELIMINARPRODUCTO            110
#define IDD_MISPRODUCTOS                113
#define IDD_COMPRARPRODUCTOS            116
#define IDD_CANCELARENVIO               118
#define IDD_EDITARPRODUCTO              119
#define IDD_MISENVIOS                   120
#define IDD_EDITARENVIO                 124
#define IDC__INFV_NOMBRECOMPLETO        1002
#define IDC_INFV_ALIAS                  1003
#define IDC_BUTTON1                     1004
#define BTN__INIS_INICIARSESION         1005
#define IDC_REG_CONTRA                  1006
#define BTN_REG_REGISTRARUSUARIO        1007
#define BTN_INFV_APLICAR                1013
#define BTN_INFV_CARGARFOTO             1014
#define IDC_REG_NOMBREUSUARIO           1016
#define IDC_INIS_USUARIO                1017
#define IDC_INIS_CONTRA                 1018
#define IDC_INIS_REGISTRARSE            1019
#define IDC_INIS_SALIR                  1020
#define IDC_REG_VOLVER                  1022
#define IDC_NUEVOPRODUCTO_VOLVER        1024
#define IDC_NUEVOPRODUCTO_NOMBRE        1025
#define IDC_NUEVOPRODUCTO_CANTIDAD      1026
#define IDC_NUEVOPRODUCTO_FOTO          1027
#define IDC_NUEVOPRODUCTO_CODIGO        1028
#define IDC_NUEVOPRODUCTO_MARCA         1029
#define IDC_NUEVOPRODUCTO_DESCRIPCION   1030
#define IDC_NUEVOPRODUCTO_MONTO         1031
#define IDC_NUEVOPRODUCTO_IMAGEN        1032
#define IDC_ELIMINARPRODUCTO_VOLVER     1033
#define IDC_ELIMINARPRODUCTO_ELIMINAR   1037
#define IDC_NUEVOPRODUCTO_REGISTRAR     1038
#define IDC_EDITARPRODUCTO_VOLVER       1039
#define IDC_EDITARPRODUCTO_EDITARFOTO1  1041
#define IDC_EDITARPRODUCTO_NOMBRE       1042
#define IDC_EDITARPRODUCTO_CANTIDADINVENTARIO 1043
#define IDC_EDITARPRODUCTO_CODIGOPRODUCTO 1044
#define IDC_EDITARPRODUCTO_MARCA        1045
#define IDC_EDITARPRODUCTO_DESCRIPCION  1046
#define IDC_EDITARPRODUCTO_MONTO        1047
#define IDC_EDITARPRODUCTO_ACEPTAR      1048
#define IDC_ELIMINARPRODUCTO_NOMBRE     1050
#define IDC_ELIMINARPRODUCTO_CANTIDAD   1051
#define IDC_ELIMINARPRODUCTO_CODIGO     1052
#define IDC_ELIMINARPRODUCTO_MARCA      1053
#define IDC_ELIMINARPRODUCTO_DESCRIPCION 1054
#define IDC_ELIMINARPRODUCTO_MONTO      1055
#define IDC_ELIMINARPRODUCTO_FOTO1      1056
#define IDC_LIST1                       1057
#define IDC_MISPRODUCTOS_NOMBRE         1058
#define IDC_MISPRODUCTOS_CANTIDAD       1059
#define IDC_MISPRODUCTOS_CODIGO         1060
#define IDC_MISPRODUCTOS_MARCA          1061
#define IDC_MISPRODUCTOS_DESCRIPCION    1062
#define IDC_MISPRODUCTOS_MONTO          1063
#define IDC_MISPRODUCTOS_IMAGEN         1064
#define IDC_MISPRODUCTOS_VOLVER         1065
#define IDC_COMPRARPRODUCTOS_ARTICULOSDISPONIBLES 1067
#define IDC_COMPRARPRODUCTOS_FECHAENVIO 1069
#define IDC_COMPRARPRODUCTOS_MONTO      1070
#define IDC_COMPRARPRODUCTOS_ORDENAR    1071
#define IDC_COMPRARPRODUCTOS_VOLVER     1072
#define IDC_COMPRARPRODUCTOS_MENSAJE    1073
#define IDC_COMPRARPRODUCTOS_ESTADO     1074
#define IDC_COMPRARPRODUCTOS_CIUDAD     1075
#define IDC_COMPRARPRODUCTOS_COLONIA    1076
#define IDC_COMPRARPRODUCTOS_CALLE      1077
#define IDC_CANCELARENVIO_LISTA         1078
#define IDC_COMPRARPRODUCTOS_CANTIDAD   1079
#define IDC_CANCELARENVIO_CANTIDAD      1080
#define IDC_CANCELARENVIO_CALLE         1081
#define IDC_CANCELARENVIO_COLONIA       1082
#define IDC_CANCELARENVIO_CIUDAD        1083
#define IDC_CANCELARENVIO_ESTADO        1084
#define IDC_CANCELARENVIO_MENSAJE       1085
#define IDC_CANCELARENVIO_ACEPTAR       1087
#define IDC_CANCELARENVIO_VOLVER        1088
#define IDC_EDITARENVIO_VOLVER          1089
#define IDC_EDITARENVIO_EDITAR          1090
#define IDC_EDITARENVIO_FECHAENVIO      1091
#define IDC_EDITARENVIO_MENSAJE         1092
#define IDC_EDITARENVIO_ESTADO          1093
#define IDC_EDITARENVIO_CIUDAD          1094
#define IDC_EDITARENVIO_COLONIA         1095
#define IDC_EDITARENVIO_CALLE           1096
#define IDC_EDITARENVIO_CANTIDAD        1097
#define IDC_EDITARENVIO_LISTA           1098
#define BTN_INFV_CARGAR                 1101
#define IDC_INFV_FOTO                   1102
#define IDC_MISPRODUCTOS_LISTA          1104
#define IDC_NUEVOPRODUCTO_FOTO2         1106
#define IDC_NUEVOPRODUCTO_IMAGEN2       1107
#define IDC_MISPRODUCTOS_IMAGEN2        1108
#define IDC_ELIMINARPRODUCTO_FOTO2      1113
#define IDC_EDITARPRODUCTO_FOTO1        1114
#define IDC_EDITARPRODUCTO_FOTO2        1115
#define IDC_EDITARPRODUCTO_EDITARFOTO2  1116
#define IDC_EDITARPRODUCTO_LISTA        1117
#define IDC_ELIMINARPRODUCTO_LISTA      1118
#define IDC_COMPRARPRODUCTOS_PRODUCTOACOMPRAR 1121
#define IDC_COMPRARPRODUCTOS_CALCULAR   1124
#define IDC_MISPRODUCTOS_GLOBAL         1132
#define IDC_MISENVIOS_STATUS            1133
#define IDC_MISENVIOS_CANTIDAD          1134
#define IDC_MISENVIOS_FECHAENVIO_DIA    1135
#define IDC_MISENVIOS_DIRECCION_CALLE   1136
#define IDC_MISENVIOS_GLOBAL            1137
#define IDC_MISENVIOS_FECHAENVIO_MES    1138
#define IDC_MISENVIOS_FECHAENVIO_ANIO   1139
#define IDC_MISENVIOS_DIRECCION_COLONIA 1140
#define IDC_MISENVIOS_DIRECCION_CIUDAD  1141
#define IDC_MISENVIOS_DIRECCION_ESTADO  1142
#define IDC_DATETIMEPICKER1             1143
#define IDC_EDIT10                      1144
#define IDC_EDIT11                      1145
#define IDC_EDIT12                      1146
#define IDC_MISENVIOS_PRODUCTO          1147
#define IDC_EDITARENVIO_DIA             1148
#define IDC_EDITARENVIO_MES             1149
#define IDC_EDITARENVIO_ANIO            1150
#define IDC_CANCELARENVIO_DIA           1151
#define IDC_CANCELARENVIO_MES           1152
#define IDC_CANCELARENVIO_ANIO          1153
#define usuario_misenvios               1154
#define usuario_misenvios_foto          1155
#define nombreusuario_nuevop            1156
#define fotousuario_nuevoproducto       1157
#define fotoeliminarusuario             1159
#define nombreusuarioeliminar           1160
#define nombreusuarioeditarproducto     1161
#define fotoeditarproductousuario       1162
#define mispusuariofoto                 1163
#define nombremispusuario               1165
#define comprarmiusuarioproducto        1166
#define fotocomprarpro                  1167
#define cancelarenvusuarioact           1168
#define fotocancelarenvusuario          1169
#define IDC_EDIT1                       1170
#define usuarioeditarenvi               1170
#define fotoeditenv                     1171
#define ID_REGISTRARSE_SALIR            40001
#define MENU_REGISTRARSE                40002
#define ID_Registro                     40003
#define ID_MENU_PRODUCTOR               40004
#define ID_MENU_ENVIOS                  40005
#define ID_MENU_SALIR                   40006
#define ID_ENVIOS_COMPRARPRODUCTOS      40007
#define ID_ENVIOS_CANCELARUNENVIO       40008
#define ID_ENVIOS_EDITARUNENVIO         40009
#define ID_ENVIOS_MISENVIOS             40010
#define ID_PRODUCTOS_NUEVOPRODUCTO      40011
#define ID_PRODUCTOS_ELIMINARPRODUCTO   40012
#define ID_PRODUCTOS_EDITARUNPRODUCTO   40013
#define ID_PRODUCTOS_MISPRODUCTOS       40014
#define ID_PRODUCTOS_NUEVOPRODUCTO40015 40015
#define ID_MENU_INFVEND                 40016
#define ID_MENU_PRODCUTOS_NUEVO         40017
#define ID_MENU_PRODCUTOS_ELIMINAR      40018
#define ID_MENU_PRODCUTOS_EDITAR        40019
#define ID_MENU_PRODCUTOS_MISPRODUCTOS  40020
#define ID_MENU_ENVIOS_COMPRAR          40021
#define ID_MENU_ENVIOS_CANCELAR         40022
#define ID_MENU_ENVIOS_EDITAR           40023
#define ID_MENU_ENVIOS_MISENVIOS        40024
#define ID_MENU_INFORMACIONVENDEDOR     40025
#define ID_MENU_CERRARSESION            40026
#define ID_MENU_CERRARSESION40027       40027
#define ID_MENU_GUARDARLISTA            40028
#define ID_MENU_CARGARLISTA             40029

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        126
#define _APS_NEXT_COMMAND_VALUE         40030
#define _APS_NEXT_CONTROL_VALUE         1172
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
